### ISSUE TITLE
Bump `omniauth-oauth2` dependency version to 1.3.1

### ISSUE THREAD

**Issue by gon** [kmrshntr/omniauth-slack#15]
I'm using `Rails-API` and running into an issue discussed in these threads
https://github.com/rails-api/rails-api/issues/73
https://github.com/rails-api/rails-api/issues/38
https://github.com/lynndylanhurley/devise_token_auth/issues/183

In fact, it looks like the `OmniAuth::NoSessionError` error does gets fixed in `omniauth-oauth2` release 1.3.1 in this commit https://github.com/intridea/omniauth-oauth2/commit/43c84c8c01b25f3a863c97af831f3d29992eb2d4 by @isaacsanders.

@kmrshntr, would you mind bumping the dependency?

**Comment by kmrshntr** [comment]
Now I released as v2.1.1.

https://github.com/kmrshntr/omniauth-slack/releases/tag/v2.1.1
https://rubygems.org/gems/omniauth-slack/versions/2.1.1
