### ISSUE TITLE
Add support to sign in with Slack

### ISSUE THREAD

**Issue by xdmx** [kmrshntr/omniauth-slack#31]
Slack has added the ability to sign in: https://api.slack.com/docs/sign-in-with-slack

The info should be fetched from `/api/users.identity` instead of `/api/auth.test` and `/api/users.info`

**Comment by JustLey** [comment]
Just a heads up, shouldn't this issue be closed?

**Comment by kmrshntr** [comment]
Year right. Thank you for letting me know.
This issue was resolved by #32.
