### ISSUE TITLE
Multiple providers

### ISSUE THREAD

**Issue by lcpriest** [kmrshntr/omniauth-slack#47]
```
provider :slack, 'API_KEY', 'API_SECRET', scope: 'identity.basic', name: :sign_in_with_slack
provider :slack, 'API_KEY', 'API_SECRET', scope: 'team:read,users:read,identify,bot'
```

How do you target the provider with name :sign_in_with_slack?

`https://somedomain.com/auth/sign_in_with_slack`?

**Comment by julienma** [comment]
Yeah, default name is `slack`, which callback URL is `/auth/slack/callback/`.

If you add another provider with a custom name, like `sign_in_with_slack`, then callback URL is `/auth/sign_in_with_slack/callback/`.

**Comment by lcpriest** [comment]
Thanks @julienma!
