### ISSUE TITLE
/auth/:provider is not defined when using name: attribute in Omniauth builder

### ISSUE THREAD

**Issue by oranges13** [kmrshntr/omniauth-slack#49]
Before adding the new Sign in with Slack options, this is how I was building my slack auth with environment vars:

(For reference, my SLACK_SCOPES are only `identity.basic`)

```ruby
use OmniAuth::Builder do
	provider :slack,
		ENV["SLACK_APP_ID"],
		ENV["SLACK_APP_KEY"],
		scope: ENV["SLACK_SCOPES"],
		team: ENV["SLACK_TEAM_ID"]
end
```

This works as expected.

When I add the `name` attribute, the route `/auth/slack` fails to respond with (404). Regardless the sign in with slack functionality works, I'm not sure if the name attribute is required for it to function.

```ruby
use OmniAuth::Builder do
	provider :slack,
		ENV["SLACK_APP_ID"],
		ENV["SLACK_APP_KEY"],
		scope: ENV["SLACK_SCOPES"],
		team: ENV["SLACK_TEAM_ID"],
		name: :sign_in_with_slack
end
```

Here are the versions from my gemfile for reference:

```
oauth2 (1.3.0)
  faraday (>= 0.8, < 0.11)
  jwt (~> 1.0)
  multi_json (~> 1.3)
  multi_xml (~> 0.5)
  rack (>= 1.2, < 3)
omniauth (1.3.2)
  hashie (>= 1.2, < 4)
  rack (>= 1.0, < 3)
omniauth-oauth2 (1.3.1)
  oauth2 (~> 1.0)
  omniauth (~> 1.2)
omniauth-slack (2.3.0)
  omniauth-oauth2 (~> 1.3.1)
```

**Comment by ginjo** [comment]
The ```:name``` attribute of the ```provider``` method changes the callback path expected by omniauth. So the callback url for your specific setup would be ```/auth/sign_in_with_slack```. You can use the ```:name``` attribute to create multiple setups for the same provider - by just using a different name for each setup.

**Comment by oranges13** [comment]
Ah! Now I feel silly. Thank you for the clarification.

**Comment by ginjo** [comment]
Glad that helped. I know I've seen the documentation for this setting, but I couldn't find it last night in the obvious places. It's somewhere in one of the three gems (omniauth, omniauth-oauth2, omniauth-slack), probably in the main omniauth gem.
