### ISSUE TITLE
Non-admin users are getting invalid_auth

### ISSUE THREAD

**Issue by marclennox** [kmrshntr/omniauth-slack#6]
I've been banging my head for a while on this one.  I'm always getting an "invalid_auth" response on the call to "auth.test" unless the slack user is an admin, regardless of what scope I provide.

I'm trying to narrow this down but having a hard time figuring where the problem is.

Any ideas?

**Comment by technicalpickles** [comment]
@marclennox what permissions do you have for configuring Integrations? It seems that permission to authenticate with OAuth is conflated with configuring Integrations.

That means you'd need to allow anyone to configure Integrations if you want anyone to OAuth against even your own OAuth application.

**Comment by marclennox** [comment]
I haven't seen this behaviour.  Anyone is able to oauth to the application, admin or not.  The original issue is not an issue for me anymore so I'm closing this.

**Comment by technicalpickles** [comment]
For reference, I just ran into this just  last week, and was told by Slack it's the expected current behavior. So it's still a problem.
